In [1]:
import numpy as np

#Function row and column parity
def compute_2D_Parity(matrix):
    row_Parity = np.sum(matrix, axis=1) % 2
    col_parity = np.sum(matrix, axis=0) % 2
    return row_Parity, col_parity

#Initialise data matrix 4x4
matrix = np.array([
   [1, 0, 1, 1],
   [0, 1, 0, 0],
   [1, 1, 1, 0],
   [0, 0, 1, 1],
])
print ("The Original Data Matrix:\n", matrix)

#calculate original parity bit
row_Parity, col_Parity = compute_2D_Parity(matrix)
print("The Row parity:", col_Parity)

#stimulate error in the matrix
error_Position = (2, 3)
matrix_with_Error = matrix.copy()
matrix_with_Error[error_Position] ^= 1

print("\nMatrix with an Error at", error_Position, ":\n", matrix_with_Error)

#Detect error using parity
new_row_parity, new_col_parity = compute_2D_Parity(matrix_with_Error)
error_row = np.where(row_Parity != new_row_parity)[0]
error_col = np.where(col_Parity != new_col_parity)[0]

if len(error_row) == 1 and len(error_col) == 1:
    error_loc = (error_row[0], error_col[0])
    print("An Error detected at:", error_loc) 
    
    #correct error
    matrix_with_Error[error_loc] ^= 1
    print("Corrected Matrix:\n", matrix_with_Error)
    
else:
    print("There are no single-bit errors or multiple errors detected.")
    
    


The Original Data Matrix:
 [[1 0 1 1]
 [0 1 0 0]
 [1 1 1 0]
 [0 0 1 1]]
The Row parity: [0 0 1 0]

Matrix with an Error at (2, 3) :
 [[1 0 1 1]
 [0 1 0 0]
 [1 1 1 1]
 [0 0 1 1]]
An Error detected at: (np.int64(2), np.int64(3))
Corrected Matrix:
 [[1 0 1 1]
 [0 1 0 0]
 [1 1 1 0]
 [0 0 1 1]]
